[general]
import = ["~/.config/alacritty/themes/themes/nord.toml"]

[window]
opacity = 0.9
decorations = "Full"
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

[font]
normal = { family = "Hurmit Nerd Font", style = "Regular" }
bold = { family = "Hurmit Nerd Font", style = "Bold" }
italic = { family = "Hurmit Nerd Font", style = "Italic" }
size = 11
# normal = {family = "Cascadia Mono"}
# size = 12
